# lab-12/db-version-1.yml
# usage:
#   ansible-playbook version-1-to-2.yml --extra-vars "host=$USER"
---
- hosts: '{{ host }}'
  gather_facts: no
  become: true
  become_user: postgres

  tasks:

  
  - name: add first column
    community.postgresql.postgresql_query:
      db: cptr245
      query: ALTER TABLE "Faculty" ADD COLUMN lastName text;

  - name: add second column
    community.postgresql.postgresql_query:
      db: cptr245
      query: ALTER TABLE "Faculty" ADD COLUMN firstName text;

  - name: update column 1
    community.postgresql.postgresql_query:
      db: cptr245
      query: UPDATE "Faculty" SET lastName = split_part(name, ', ', 1);

  - name: update column 2
    community.postgresql.postgresql_query:
      db: cptr245
      query: UPDATE "Faculty" SET firstName = split_part(name, ', ', 2);

  - name: remove old column
    community.postgresql.postgresql_query:
      db: cptr245
      query: Alter TABLE "Faculty" DROP COLUMN name;

  - name: update database
    community.postgresql.postgresql_query:
      db: cptr245
      query: UPDATE "DbVersion" SET version = 2;


  - name: Install application version 2
    become: true
    become_user: root
    copy:
      src: "files/listFaculty2.py"
      dest: "/usr/lib/cgi-bin/listFaculty.py"
      mode: '0755'
